version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: yashparmar2055/elite-backend:latest
    container_name: elite-backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DATABASE_URL: mongodb+srv://username:password@cluster0.awnwlcz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      
    depends_on:
      - mongo

  frontend:
    image: yashparmar2055/elite-frontend:latest
    container_name: elite-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
